<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NvEncSharp/NvEncSharp.csproj" AdditionalProperties="BuildCudaLibrary=false;GeneratePackageOnBuild=false;CopyNativeHelpers=false" />
  </ItemGroup>
</Project>
