using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using static Lennox.NvEncSharp.Test.CodeGeneration;

namespace Lennox.NvEncSharp.Test
{
    [TestClass]
    public class NativeSizeTests
    {
        private static IEnumerable<string> NativeStructs(string header) =>
            Regex.Matches(header, @"typedef\s+(?:struct|union)\s+_\w+\s*\{.*?^}\s*(\w+)",
                    RegexOptions.Singleline | RegexOptions.Multiline)
                .Cast<Match>().Select(m => m.Groups[1].Value).Distinct();

        private static string ManagedName(string native) => native == "GUID" ? "Guid"
            : native == "NV_ENCODE_API_FUNCTION_LIST" ? "NvEncApiFunctionList" : Fixname(native);

        private static Type[] Delegates() => typeof(NvEncApiFunctionList).GetNestedTypes()
            .Where(t => typeof(Delegate).IsAssignableFrom(t)).OrderBy(t => t.Name).ToArray();

        private static string HeaderHash(string header)
        {
            using var sha = SHA256.Create();
            return BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(header)))
                .Replace("-", "");
        }

        // Called by GenerateStructs. This emits source only; native compilation is manual.
        internal static void GenerateProbe()
        {
            var header = LoadNvencHeader();
            var output = new StringBuilder(@"// Generated by NativeSizeTests.GenerateProbe. Do not edit.
// Once off, from an x64 MSVC developer prompt in this directory:
// cl /nologo /EHsc /std:c++17 NativeSizes.cpp /Foobj\NativeSizes.obj /Feobj\NativeSizes.exe
// obj\NativeSizes.exe > NativeSizes.windows-x64.txt
#include <windows.h>
#include ""nvEncodeAPI.h""
#include <iostream>
#include <type_traits>
#include <utility>
static_assert(sizeof(void*) == 8, ""Capture the Windows x64 ABI"");

template<class T> void argument(const char* name, size_t index) {
    std::cout << name << "".arg"" << index << ' ' << sizeof(T) << '\n';
    if constexpr (std::is_pointer_v<T> && !std::is_void_v<std::remove_pointer_t<T>>) {
        std::cout << name << "".arg"" << index << "".pointee ""
                  << sizeof(std::remove_pointer_t<T>) << '\n';
    }
}
template<class T> struct signature;
template<class R, class... A> struct signature<R (NVENCAPI*)(A...)> {
    template<size_t... I> static void arguments(const char* name, std::index_sequence<I...>) {
        (argument<A>(name, I), ...);
    }
    static void print(const char* name) {
        std::cout << name << "".count "" << sizeof...(A) << '\n';
        std::cout << name << "".return "" << sizeof(R) << '\n';
        arguments(name, std::index_sequence_for<A...>{});
    }
};
int main() {
");
            output.AppendLine($"    std::cout << \"# nvEncodeAPI.h SHA256 {HeaderHash(header)}\\n\";");
            foreach (var native in NativeStructs(header))
                output.AppendLine($"    std::cout << \"{ManagedName(native)} \" << sizeof({native}) << '\\n';");
            foreach (var type in Delegates())
            {
                var native = "PNVENC" + type.Name.Substring(0, type.Name.Length - 2).ToUpperInvariant();
                if (!Regex.IsMatch(header, @"\b" + native + @"\b"))
                    throw new InvalidOperationException($"No native signature for {type.Name}");
                output.AppendLine($"    signature<{native}>::print(\"{type.Name}\");");
            }
            output.AppendLine("}");
            output.Replace("\r\n", "\n").Replace("\n", "\r\n");
            WriteNvencHeaderOutput(output, "../NvEncSharp.Test/NativeSizes.cpp");
        }

        private static int NativeSize(Type type)
        {
            if (type.IsPointer || type.IsByRef) return IntPtr.Size;
            return Marshal.SizeOf(type.IsEnum ? Enum.GetUnderlyingType(type) : type);
        }

        [TestMethod]
        public void ManagedSizesMatchNativeWindowsX64()
        {
            if (Environment.OSVersion.Platform != PlatformID.Win32NT || IntPtr.Size != 8)
                Assert.Inconclusive("The captured native ABI is Windows x64 only.");

            var assembly = typeof(NativeSizeTests).Assembly;
            var resource = assembly.GetManifestResourceNames()
                .Single(n => n.EndsWith("NativeSizes.windows-x64.txt"));
            using var stream = assembly.GetManifestResourceStream(resource);
            using var reader = new StreamReader(stream);
            var header = LoadNvencHeader();
            Assert.AreEqual("# nvEncodeAPI.h SHA256 " + HeaderHash(header), reader.ReadLine(),
                "Header changed: regenerate and manually compile/run NativeSizes.cpp.");
            var sizes = new Dictionary<string, int>();
            string line;
            while ((line = reader.ReadLine()) != null)
            {
                var parts = line.Split(' ');
                Assert.AreEqual(2, parts.Length, line);
                sizes.Add(parts[0], int.Parse(parts[1], CultureInfo.InvariantCulture));
            }

            void Check(string key, int actual)
            {
                Assert.IsTrue(sizes.TryGetValue(key, out var expected), "Missing native size: " + key);
                Assert.AreEqual(expected, actual, key);
                sizes.Remove(key);
            }

            foreach (var native in NativeStructs(header))
            {
                var name = ManagedName(native);
                var type = name == "Guid" ? typeof(Guid)
                    : typeof(NvEncoder).Assembly.GetType("Lennox.NvEncSharp." + name, true);
                Check(name, NativeSize(type));
            }
            foreach (var type in Delegates())
            {
                var invoke = type.GetMethod("Invoke");
                var parameters = invoke.GetParameters();
                Check(type.Name + ".count", parameters.Length);
                Check(type.Name + ".return", NativeSize(invoke.ReturnType));
                for (var i = 0; i < parameters.Length; ++i)
                {
                    var key = type.Name + ".arg" + i;
                    var parameterType = parameters[i].ParameterType;
                    Check(key, NativeSize(parameterType));
                    if (sizes.ContainsKey(key + ".pointee"))
                    {
                        Assert.IsTrue(parameterType.IsByRef || parameterType.IsPointer,
                            key + " must expose a typed pointer/ref/out parameter.");
                        Check(key + ".pointee", NativeSize(parameterType.GetElementType()));
                    }
                }
            }
            Assert.AreEqual(0, sizes.Count, "Unverified native entries: " + string.Join(", ", sizes.Keys));
        }
    }
}
