// Generated by NativeSizeTests.GenerateProbe. Do not edit.
// Once off, from an x64 MSVC developer prompt in this directory:
// cl /nologo /EHsc /std:c++17 NativeSizes.cpp /Foobj\NativeSizes.obj /Feobj\NativeSizes.exe
// obj\NativeSizes.exe > NativeSizes.windows-x64.txt
#include <windows.h>
#include "nvEncodeAPI.h"
#include <iostream>
#include <type_traits>
#include <utility>
static_assert(sizeof(void*) == 8, "Capture the Windows x64 ABI");

template<class T> void argument(const char* name, size_t index) {
    std::cout << name << ".arg" << index << ' ' << sizeof(T) << '\n';
    if constexpr (std::is_pointer_v<T> && !std::is_void_v<std::remove_pointer_t<T>>) {
        std::cout << name << ".arg" << index << ".pointee "
                  << sizeof(std::remove_pointer_t<T>) << '\n';
    }
}
template<class T> struct signature;
template<class R, class... A> struct signature<R (NVENCAPI*)(A...)> {
    template<size_t... I> static void arguments(const char* name, std::index_sequence<I...>) {
        (argument<A>(name, I), ...);
    }
    static void print(const char* name) {
        std::cout << name << ".count " << sizeof...(A) << '\n';
        std::cout << name << ".return " << sizeof(R) << '\n';
        arguments(name, std::index_sequence_for<A...>{});
    }
};
int main() {
    std::cout << "# nvEncodeAPI.h SHA256 ACB3F23D22BF02C5FABF3D22B32D2653FED4CFC6CDA259B48B23D485834B02E8\n";
    std::cout << "Guid " << sizeof(GUID) << '\n';
    std::cout << "NvEncRect " << sizeof(NVENC_RECT) << '\n';
    std::cout << "NvEncCapsParam " << sizeof(NV_ENC_CAPS_PARAM) << '\n';
    std::cout << "NvEncRestoreEncoderStateParams " << sizeof(NV_ENC_RESTORE_ENCODER_STATE_PARAMS) << '\n';
    std::cout << "NvEncOutputStatsBlock " << sizeof(NV_ENC_OUTPUT_STATS_BLOCK) << '\n';
    std::cout << "NvEncOutputStatsRow " << sizeof(NV_ENC_OUTPUT_STATS_ROW) << '\n';
    std::cout << "NvEncEncodeOutParams " << sizeof(NV_ENC_ENCODE_OUT_PARAMS) << '\n';
    std::cout << "NvEncLookaheadPicParams " << sizeof(NV_ENC_LOOKAHEAD_PIC_PARAMS) << '\n';
    std::cout << "NvEncCreateInputBuffer " << sizeof(NV_ENC_CREATE_INPUT_BUFFER) << '\n';
    std::cout << "NvEncCreateBitstreamBuffer " << sizeof(NV_ENC_CREATE_BITSTREAM_BUFFER) << '\n';
    std::cout << "NvEncMvector " << sizeof(NV_ENC_MVECTOR) << '\n';
    std::cout << "NvEncH264MvData " << sizeof(NV_ENC_H264_MV_DATA) << '\n';
    std::cout << "NvEncHevcMvData " << sizeof(NV_ENC_HEVC_MV_DATA) << '\n';
    std::cout << "NvEncCreateMvBuffer " << sizeof(NV_ENC_CREATE_MV_BUFFER) << '\n';
    std::cout << "NvEncQp " << sizeof(NV_ENC_QP) << '\n';
    std::cout << "NvEncClockTimestampSet " << sizeof(NV_ENC_CLOCK_TIMESTAMP_SET) << '\n';
    std::cout << "NvEncTimeCode " << sizeof(NV_ENC_TIME_CODE) << '\n';
    std::cout << "NvEncConfigH264VuiParameters " << sizeof(NV_ENC_CONFIG_H264_VUI_PARAMETERS) << '\n';
    std::cout << "NvEncExternalMeHintCountsPerBlocktype " << sizeof(NVENC_EXTERNAL_ME_HINT_COUNTS_PER_BLOCKTYPE) << '\n';
    std::cout << "NvEncExternalMeHint " << sizeof(NVENC_EXTERNAL_ME_HINT) << '\n';
    std::cout << "NvEncExternalMeSbHint " << sizeof(NVENC_EXTERNAL_ME_SB_HINT) << '\n';
    std::cout << "NvEncConfigH264 " << sizeof(NV_ENC_CONFIG_H264) << '\n';
    std::cout << "NvEncConfigHevc " << sizeof(NV_ENC_CONFIG_HEVC) << '\n';
    std::cout << "NvEncFilmGrainParamsAv1 " << sizeof(NV_ENC_FILM_GRAIN_PARAMS_AV1) << '\n';
    std::cout << "NvEncConfigAv1 " << sizeof(NV_ENC_CONFIG_AV1) << '\n';
    std::cout << "NvEncConfigH264Meonly " << sizeof(NV_ENC_CONFIG_H264_MEONLY) << '\n';
    std::cout << "NvEncConfigHevcMeonly " << sizeof(NV_ENC_CONFIG_HEVC_MEONLY) << '\n';
    std::cout << "NvEncCodecConfig " << sizeof(NV_ENC_CODEC_CONFIG) << '\n';
    std::cout << "NvEncConfig " << sizeof(NV_ENC_CONFIG) << '\n';
    std::cout << "NvEncInitializeParams " << sizeof(NV_ENC_INITIALIZE_PARAMS) << '\n';
    std::cout << "NvEncReconfigureParams " << sizeof(NV_ENC_RECONFIGURE_PARAMS) << '\n';
    std::cout << "NvEncPresetConfig " << sizeof(NV_ENC_PRESET_CONFIG) << '\n';
    std::cout << "NvEncPicParamsMvc " << sizeof(NV_ENC_PIC_PARAMS_MVC) << '\n';
    std::cout << "NvEncPicParamsH264Ext " << sizeof(NV_ENC_PIC_PARAMS_H264_EXT) << '\n';
    std::cout << "NvEncSeiPayload " << sizeof(NV_ENC_SEI_PAYLOAD) << '\n';
    std::cout << "NvEncPicParamsH264 " << sizeof(NV_ENC_PIC_PARAMS_H264) << '\n';
    std::cout << "NvEncPicParamsHevc " << sizeof(NV_ENC_PIC_PARAMS_HEVC) << '\n';
    std::cout << "NvEncPicParamsAv1 " << sizeof(NV_ENC_PIC_PARAMS_AV1) << '\n';
    std::cout << "NvEncCodecPicParams " << sizeof(NV_ENC_CODEC_PIC_PARAMS) << '\n';
    std::cout << "NvEncPicParams " << sizeof(NV_ENC_PIC_PARAMS) << '\n';
    std::cout << "NvEncMeonlyParams " << sizeof(NV_ENC_MEONLY_PARAMS) << '\n';
    std::cout << "NvEncLockBitstream " << sizeof(NV_ENC_LOCK_BITSTREAM) << '\n';
    std::cout << "NvEncLockInputBuffer " << sizeof(NV_ENC_LOCK_INPUT_BUFFER) << '\n';
    std::cout << "NvEncMapInputResource " << sizeof(NV_ENC_MAP_INPUT_RESOURCE) << '\n';
    std::cout << "NvEncInputResourceOpenglTex " << sizeof(NV_ENC_INPUT_RESOURCE_OPENGL_TEX) << '\n';
    std::cout << "NvEncFencePointD3d12 " << sizeof(NV_ENC_FENCE_POINT_D3D12) << '\n';
    std::cout << "NvEncInputResourceD3d12 " << sizeof(NV_ENC_INPUT_RESOURCE_D3D12) << '\n';
    std::cout << "NvEncOutputResourceD3d12 " << sizeof(NV_ENC_OUTPUT_RESOURCE_D3D12) << '\n';
    std::cout << "NvEncRegisterResource " << sizeof(NV_ENC_REGISTER_RESOURCE) << '\n';
    std::cout << "NvEncStat " << sizeof(NV_ENC_STAT) << '\n';
    std::cout << "NvEncSequenceParamPayload " << sizeof(NV_ENC_SEQUENCE_PARAM_PAYLOAD) << '\n';
    std::cout << "NvEncEventParams " << sizeof(NV_ENC_EVENT_PARAMS) << '\n';
    std::cout << "NvEncOpenEncodeSessionExParams " << sizeof(NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS) << '\n';
    std::cout << "NvEncApiFunctionList " << sizeof(NV_ENCODE_API_FUNCTION_LIST) << '\n';
    signature<PNVENCCREATEBITSTREAMBUFFER>::print("CreateBitstreamBufferFn");
    signature<PNVENCCREATEINPUTBUFFER>::print("CreateInputBufferFn");
    signature<PNVENCCREATEMVBUFFER>::print("CreateMvBufferFn");
    signature<PNVENCDESTROYBITSTREAMBUFFER>::print("DestroyBitstreamBufferFn");
    signature<PNVENCDESTROYENCODER>::print("DestroyEncoderFn");
    signature<PNVENCDESTROYINPUTBUFFER>::print("DestroyInputBufferFn");
    signature<PNVENCDESTROYMVBUFFER>::print("DestroyMvBufferFn");
    signature<PNVENCENCODEPICTURE>::print("EncodePictureFn");
    signature<PNVENCGETENCODECAPS>::print("GetEncodeCapsFn");
    signature<PNVENCGETENCODEGUIDCOUNT>::print("GetEncodeGuidCountFn");
    signature<PNVENCGETENCODEGUIDS>::print("GetEncodeGuidsFn");
    signature<PNVENCGETENCODEPRESETCONFIGEX>::print("GetEncodePresetConfigExFn");
    signature<PNVENCGETENCODEPRESETCONFIG>::print("GetEncodePresetConfigFn");
    signature<PNVENCGETENCODEPRESETCOUNT>::print("GetEncodePresetCountFn");
    signature<PNVENCGETENCODEPRESETGUIDS>::print("GetEncodePresetGuidsFn");
    signature<PNVENCGETENCODEPROFILEGUIDCOUNT>::print("GetEncodeProfileGuidCountFn");
    signature<PNVENCGETENCODEPROFILEGUIDS>::print("GetEncodeProfileGuidsFn");
    signature<PNVENCGETENCODESTATS>::print("GetEncodeStatsFn");
    signature<PNVENCGETINPUTFORMATCOUNT>::print("GetInputFormatCountFn");
    signature<PNVENCGETINPUTFORMATS>::print("GetInputFormatsFn");
    signature<PNVENCGETLASTERROR>::print("GetLastErrorFn");
    signature<PNVENCGETSEQUENCEPARAMS>::print("GetSequenceParamsFn");
    signature<PNVENCINITIALIZEENCODER>::print("InitializeEncoderFn");
    signature<PNVENCINVALIDATEREFFRAMES>::print("InvalidateRefFramesFn");
    signature<PNVENCLOCKBITSTREAM>::print("LockBitstreamFn");
    signature<PNVENCLOCKINPUTBUFFER>::print("LockInputBufferFn");
    signature<PNVENCMAPINPUTRESOURCE>::print("MapInputResourceFn");
    signature<PNVENCOPENENCODESESSIONEX>::print("OpenEncodeSessionExFn");
    signature<PNVENCOPENENCODESESSION>::print("OpenEncodeSessionFn");
    signature<PNVENCRECONFIGUREENCODER>::print("ReconfigureEncoderFn");
    signature<PNVENCREGISTERASYNCEVENT>::print("RegisterAsyncEventFn");
    signature<PNVENCREGISTERRESOURCE>::print("RegisterResourceFn");
    signature<PNVENCRUNMOTIONESTIMATIONONLY>::print("RunMotionEstimationOnlyFn");
    signature<PNVENCSETIOCUDASTREAMS>::print("SetIOCudaStreamsFn");
    signature<PNVENCUNLOCKBITSTREAM>::print("UnlockBitstreamFn");
    signature<PNVENCUNLOCKINPUTBUFFER>::print("UnlockInputBufferFn");
    signature<PNVENCUNMAPINPUTRESOURCE>::print("UnmapInputResourceFn");
    signature<PNVENCUNREGISTERASYNCEVENT>::print("UnregisterAsyncEventFn");
    signature<PNVENCUNREGISTERRESOURCE>::print("UnregisterResourceFn");
}